# Generated by Django 5.2 on 2025-04-24 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosEntrenar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('distanciaFrontal', models.FloatField()),
                ('ditanciaLateral', models.FloatField()),
                ('ditanciaInferior', models.FloatField()),
                ('aceleraciónX', models.FloatField()),
                ('aceleraciónY', models.FloatField()),
                ('aceleraciónZ', models.FloatField()),
                ('velodidadPala', models.FloatField()),
                ('dirrecciónGolpe', models.FloatField()),
                ('pelotaDetectada', models.BooleanField()),
                ('redDetectada', models.BooleanField()),
                ('alturaRed', models.FloatField()),
                ('velocidadPelota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='datosIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadPelota', models.FloatField(default=0.0)),
                ('tipo', models.TextField(default='')),
                ('errorNoForzado', models.BooleanField(default=False)),
                ('calidad', models.IntegerField(default=0)),
                ('idSesión', models.IntegerField(default=0)),
                ('tiempo', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.TimeField(default=django.utils.timezone.now)),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now)),
                ('numeroDeGolpes', models.IntegerField(default=0)),
                ('erroresforzados', models.FloatField(default=0.0)),
                ('idUsuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=25)),
                ('device_id2', models.CharField(default='', max_length=255)),
                ('nombre', models.TextField(default='')),
                ('altura', models.FloatField(default=0.0)),
                ('peso', models.FloatField(default=0.0)),
                ('contraseña', models.BooleanField(default=False)),
                ('manoDominanate', models.TextField(default='derecha')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
