# Generated by Django 5.2 on 2025-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='manoDominanate',
            field=models.BooleanField(default=False),
        ),
    ]
