# Generated by Django 5.2 on 2025-04-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padel_stats', '0002_alter_usuarios_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='user',
        ),
    ]
