# Generated by Django 5.2 on 2025-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_stats', '0003_remove_usuarios_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesiones',
            old_name='tiempo',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='sesiones',
            old_name='numeroDeGolpes',
            new_name='numGolpes',
        ),
        migrations.AddField(
            model_name='sesiones',
            name='calidadMedia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpeCalidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpeCalidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sesiones',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
