# Generated by Django 5.2.3 on 2025-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padel_stats", "0005_remove_datosentrenar_aceleraciónx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuenciaGolpe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("roll", models.FloatField()),
                ("pitch", models.FloatField()),
                ("yaw", models.FloatField()),
                ("AceleraciónX", models.FloatField()),
                ("AceleraciónY", models.FloatField()),
                ("AceleraciónZ", models.FloatField()),
                ("VelocidadPala", models.FloatField()),
                ("DistanciaFrontal", models.FloatField()),
                ("DistanciaLateral", models.FloatField()),
                ("DistanciaInferior", models.FloatField()),
                ("AlturaRed", models.FloatField(default=0.0)),
                ("DirecciónGolpe", models.FloatField(default=0.0)),
                ("VelocidadPelota", models.FloatField(default=0.0)),
                ("tipo_golpe", models.CharField(max_length=50, null=True)),
                ("errorNoForzado", models.BooleanField(null=True)),
                ("calidad", models.FloatField(null=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="device_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
