# Generated by Django 5.2.3 on 2025-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padel_stats", "0006_secuenciagolpe_alter_usuarios_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="datosSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll", models.FloatField(default=0.0)),
                ("pitch", models.FloatField(default=0.0)),
                ("yaw", models.FloatField(default=0.0)),
                ("DistanciaFrontal", models.FloatField(default=0.0)),
                ("DitanciaLateral", models.FloatField(default=0.0)),
                ("DitanciaInferior", models.FloatField(default=0.0)),
                ("AceleraciónX", models.FloatField(default=0.0)),
                ("AceleraciónY", models.FloatField(default=0.0)),
                ("AceleraciónZ", models.FloatField(default=0.0)),
                ("VelodidadPala", models.FloatField(default=0.0)),
                ("DirrecciónGolpe", models.FloatField(default=0.0)),
                ("AlturaRed", models.FloatField(default=0.0)),
                ("VelocidadPelota", models.FloatField(default=0.0)),
                ("altura", models.IntegerField(default=0)),
                ("peso", models.IntegerField(default=0)),
                ("sesionId", models.IntegerField(default=0)),
            ],
        ),
    ]
