# Generated by Django 5.2.3 on 2025-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("padel_stats", "0007_datossensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datossensor",
            name="AceleraciónX",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="AceleraciónY",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="AceleraciónZ",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="AlturaRed",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="DirrecciónGolpe",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="DistanciaFrontal",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="DitanciaInferior",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="DitanciaLateral",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="VelocidadPelota",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="VelodidadPala",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="pitch",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="roll",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="datossensor",
            name="yaw",
            field=models.JSONField(default=list),
        ),
    ]
