# Generated by Django 5.2.4 on 2025-07-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_stats', '0008_alter_datossensor_aceleraciónx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosentrenar',
            name='tipo',
            field=models.TextField(default=''),
        ),
    ]
