# Generated by Django 6.0 on 2026-01-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padel_stats', '0009_datosentrenar_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosia',
            old_name='velocidadPelota',
            new_name='velocidadBola',
        ),
        migrations.RemoveField(
            model_name='datosia',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='datosia',
            name='errorNoForzado',
        ),
        migrations.AddField(
            model_name='datosia',
            name='efecto',
            field=models.CharField(default='plano', max_length=20),
        ),
        migrations.AddField(
            model_name='datosia',
            name='exigenciaFisica',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='datosia',
            name='posibilidadLesion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datosia',
            name='potencia',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='datosia',
            name='precision',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='datosia',
            name='puntoImpacto',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='datosia',
            name='tecnica',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='exigenciaFisicaMedia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpePotencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpePrecision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpePuntoImpacto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='mejorGolpeTecnica',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpePotencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpePrecision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpePuntoImpacto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='peorGolpeTecnica',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='posibilidadLesionMedia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='velocidadBolaMaxima',
            field=models.FloatField(default=0.0),
        ),
    ]
